-- MySQL Script generated by MySQL Workbench
-- 04/25/16 11:38:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_user_downloads
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_user_downloads
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_user_downloads` ;
USE `db_user_downloads` ;

-- -----------------------------------------------------
-- Table `db_user_downloads`.`tbl_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_user_downloads`.`tbl_users` (
  `user_id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(60) NOT NULL,
  `last_name` VARCHAR(60) NOT NULL,
  `email_address` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX (`email_address` ASC));


-- -----------------------------------------------------
-- Table `db_user_downloads`.`tbl_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_user_downloads`.`tbl_product` (
  `product_id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`product_id`));


-- -----------------------------------------------------
-- Table `db_user_downloads`.`tbl_downloads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_user_downloads`.`tbl_downloads` (
  `file_name` VARCHAR(60) NOT NULL,
  `download_date_time` DATETIME NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  INDEX `downloads_fk_users` (`user_id` ASC),
  INDEX `downloads_fk_product` (`product_id` ASC),
  CONSTRAINT `downloads_fk_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_user_downloads`.`tbl_users` (`user_id`),
  CONSTRAINT `downloads_fk_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `db_user_downloads`.`tbl_product` (`product_id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
